### ISSUE TITLE
Infrared and near-infrared bands in AIDE

### ISSUE THREAD

**Issue by mikeyEcology** [microsoft/aerial_wildlife_detection#16]
Hi,
Thank you for creating this annotation software; I think it will be really helpful for our project. I'm wondering if it is possible to view infrared (IR) and near-infrared (NIR), and potentially their ratio, bands in the software. We have an aerial image dataset where some objects are only visible to a human by looking at the ratio of the NIR to IR. Our dataset has 5 channels: Red, Green, Blue, IR, and NIR. Is this something that is possible with AIDE? Or is it a feature that you would consider adding? I didn't see this capability in the demo, but I'm sorry if it is already available and I missed it. 
Thank you,
Mikey

**Comment by bkellenb** [comment]
Hello Mikey,

Thank you very much for your interest and message! It is great to see for us that our software is used for more and more different applications.
At the moment, AIDE indeed only supports web-compliant images (i.e., up to three bands and in formats like JPEG, PNG, etc., sans TIFF). However, we are aware of the interests of the remote sensing community, and we have fixed plans on implementing support for multi-band data in a future release of the platform.
For the time being, a possible workaround is to manually preprocess the images and select three bands (or indices) to use; e.g. red, green, and the band ratio or NDVI, and convert those to 24 bit JPEG images with numerical ranges of [0,255]. Of course, model performance may be limited, but if the objects of interest are mostly visible in the band ratio images, it may still work.

Thanks again for your message. Please feel free to ask us if you have any further questions.

Best regards,
Benjamin

**Comment by mikeyEcology** [comment]
Thank you for your response and suggestion @bkellenb . I'll give this a try and see how it goes.

**Comment by patrickcgray** [comment]
Hey @bkellenb is this still the case? 3 channel imagery only? Or has there been an update?
