### ISSUE TITLE
display file name with image

### ISSUE THREAD

**Issue by mikeyEcology** [microsoft/aerial_wildlife_detection#21]
Hi,
I'm wondering if it's possible to set up the interface such that the file name can be displayed somewhere on the screen along with the image. I ask because the object in my images is very hard to see, and I want the technicians to be able to go look at some other files associated with the image file if necessary.
Thank you,
Mikey

**Comment by bkellenb** [comment]
Hi Mikey,

Thank you for your suggestion. I have noted down the feature request and will implement it in time. You may stay tuned; the issue here will be closed once this is implemented!

**Comment by mikeyEcology** [comment]
Great. Thank you @bkellenb!

**Comment by bkellenb** [comment]
Dear Mikey,

The latest version of AIDE (ver. 1.9.201001b) now includes the option to automatically display the ﬁle names below the image(s), optionally as a clickable link to the URL.
This feature is disabled by default. To enable it, check the new options in the project configuration page (project > "Configuration" > "Interface" > section "General").

**Comment by mikeyEcology** [comment]
Awesome! Thank you so much @bkellenb
