### ISSUE TITLE
Cannot iterate over empty image table

### ISSUE THREAD

**Issue by frafra** [microsoft/aerial_wildlife_detection#35]
https://github.com/microsoft/aerial_wildlife_detection/blob/de150d03e267676876554f62188689cf4196f4bb/projectCreation/import_images.py#L83

This code cannot handle an empty image table. Here is a quick fix:

```python
 imgs_existing = set([i['filename'] for i in imgs_existing or []])
```

**Comment by bkellenb** [comment]
Thank you! I have resolved the issue; I decided to make the code a bit more explicit and added an if/else for readability.
