### ISSUE TITLE
kombu.five has been dropped from Kombu 5.0.0 and greater

### ISSUE THREAD

**Issue by frafra** [microsoft/aerial_wildlife_detection#36]
https://github.com/microsoft/aerial_wildlife_detection/blob/de150d03e267676876554f62188689cf4196f4bb/modules/AIController/backend/messageProcessor.py#L30

https://docs.celeryproject.org/projects/kombu/en/stable/changelog.html#version-5-0-0

`kombu==4.6.11` should be added to the requirements until the old Python 2 code is dropped.

**Comment by bkellenb** [comment]
Hi,

Thanks for raising the issue. In fact the only dependency on kombu.ﬁve was the use of the monotonic time clock, but the ofﬁcial Kombu documentation sees this replaced with `time.monotonic()` anyway.
The latest commit [#54e4662](https://github.com/microsoft/aerial_wildlife_detection/commit/54e46628333120e353257119fd9d6c5718757272) therefore sees kombu dropped from the requirements list (it's automatically installed by Celery). I also removed the version speciﬁer for Celery. A quick test with a new Conda environment showed no conﬂicts, but should any more issues arise I can re-introduce the version requirement.
