### ISSUE TITLE
Integrate this labeling with MS VOTT

### ISSUE THREAD

**Issue by JCAAUSFRA** [microsoft/aerial_wildlife_detection#4]
https://github.com/microsoft/VoTT/issues

why don't you look at integrating this labelling system with MS VOTT (Link above).

**Comment by agentmorris** [comment]
Thanks for your suggestion!  VoTT is a great tool and we use it in our own work too.  Right now AIde is really about figuring out the workflows, architectures, and active learning algorithms that will work well for conservation applications, but in the long run, integration with VoTT may make a lot of sense, either direct integration, or - more likely - contributing some of what we learn on the active learning side to VoTT's development team.

But for now, we want to focus specifically on conservation applications, so we need a bit more agility.  Closing for now, thanks!
