### ISSUE TITLE
admin password - invalid salt

### ISSUE THREAD

**Issue by ctorney** [microsoft/aerial_wildlife_detection#55]
Hi Beni
I'm getting an error when running the setupDB script 

Seems like this change 97ee9fc0e300e7236cb33240954cacf0d5eed7ea makes the new account creation here:
https://github.com/microsoft/aerial_wildlife_detection/blob/c3fade9b3a9f52a6fc31b671a6da8099bdfa9772/setup/setupDB.py#L61-L69
inconsistent with the checkpw function

**Comment by dejmail** [comment]
I'm experiencing this error as well. I can get the docker image to start but cannot login

**Comment by ctorney** [comment]
I got around this by making the following change to setupDB.py
```
68         adminHash = bcrypt.hashpw(adminPass.encode('utf8'), bcrypt.gensalt(12))
69         values = (adminName, adminEmail, adminHash, True,)
70         dbConn.execute(sql, values, None)
```

**Comment by dejmail** [comment]
Thanks for the reply. 
Were you getting the Invalid salt error on the startup as well, or just when running setupDB script ?

This didn't seem to help me though. Are you also using docker (though not sure why that would affect things)?

**Comment by ctorney** [comment]
As I remember it I'd get the error when running the setupDB script - AIDE would still launch but I couldn't log in. It was a few weeks ago now so not too sure. With that fix above the log in works with the details in the ini file.

This was with docker but I had to delete the container and start again for the change to have an effect - once you have an unencrypted admin password in the database then the setup script seems to give the salt error

**Comment by dejmail** [comment]
You get a high five for that ! It works now. I was going down the rabbit hole of middleware etc and it wasn't leading anywhere.

**Comment by bkellenb** [comment]
Hi all,

Apologies for that hiccup. I had ﬁxed it a while ago, but only in the latest [beta v3.0](https://github.com/microsoft/aerial_wildlife_detection/tree/v3.0).
It is now ﬁxed in the current stable version too; see commit [#b0319d7](https://github.com/microsoft/aerial_wildlife_detection/commit/b0319d742c7ec7e5d3d4908756c8d964575cb5f9).
