### ISSUE TITLE
loading images failed

### ISSUE THREAD

**Issue by AllenDun** [microsoft/aerial_wildlife_detection#6]
hi, intestesting work. I followed the instructions to try the aide on my ubuntu 16.04, conda environment. I ran all the aide services on a single machine. Everything was good, but it failed to load images in the labelUI. I found that the images already had been added to the database(by running "python projectCreation/import_YOLO_dataset.py" or "python projectCreation/import_images.py"). Any idea about the problem?Thanks very much

**Comment by AllenDun** [comment]
oh,  it's the problem of the configuration of settings.ini

**Comment by YangZhang-mizzou** [comment]
Hello. I find the similar problem. Could you tell me which configuration in settings.ini should be modified?
