### ISSUE TITLE
how to specify classes

### ISSUE THREAD

**Issue by ctorney** [microsoft/aerial_wildlife_detection#8]
If using AIde as an annotator only (i.e. no AI backend) how are the classes specified? I can see there is a labelclass table but can't see where the classes are defined (except from the AI models)

**Comment by bkellenb** [comment]
Hi,

The label classes are specified in the database schema of the project (relation "labelclass"). At the moment, classes are either added with the import scripts (e.g. `projectCreation/import_yolo_dataset.py`), or have to be added directly to the database, e.g. through pgAdmin4. We are currently working on a GUI implementation for specifying project settings and data, including labelclasses, directly.
